- pairs:
    spot:
      - BTC/USD
      - ETH/USD
      - DAI/USD
      - LORDS/USD
  time_difference: 120
  price_deviation: 0.0025

- pairs:
    future:
      - BTC/USD
      - ETH/USD
  time_difference: 600
  price_deviation: 0.05