from .ascendex import AscendexFetcher
from .binance import BinanceFetcher
from .bitstamp import BitstampFetcher
from .bybit import BybitFetcher
from .cex import CexFetcher
from .coinbase import CoinbaseFetcher
from .coingecko import CoingeckoFetcher
from .defillama import DefillamaFetcher
from .gecko import GeckoTerminalFetcher
from .gemini import GeminiFetcher
from .huobi import HuobiFetcher
from .kaiko import KaikoFetcher
from .kucoin import KucoinFetcher
from .okx import OkxFetcher
from .propeller import PropellerFetcher
from .starknetamm import StarknetAMMFetcher
from .thegraph import TheGraphFetcher
