version: 2

build:
  os: "ubuntu-22.04"
  apt_packages:
    - libgmp3-dev
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - python -m pip install poetry
    post_install:
      # Install only dependencies including docs
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - cd pragma-sdk && VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs && cd ..

sphinx:
  configuration: pragma-sdk/docs/source/conf.py
  fail_on_warning: true