version: 2

build:
  os: "ubuntu-22.04"
  apt_packages:
    - libgmp3-dev
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      # Install uv
      # https://docs.astral.sh/uv/
      - python -m pip install uv
    post_install:
      # Install only dependencies including docs
      - cd pragma-sdk && VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras && cd ..

sphinx:
  configuration: pragma-sdk/docs/source/conf.py
  fail_on_warning: true
