[tool.poetry]
name = "pragma-monorepo"
version = "2.0.0"
description = "Monorepo container"
license = "MIT"
authors = ["0xevolve <matthias@pragma.build>"]
readme = "README.md"
include = ["VERSION", "README.md"]
package-mode = false

[build-system]
requires = ["poetry_core>=1.8.0"]
build-backend = "poetry.core.masonry.api"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.2.0"
tag_format = "v$version"
version_files = [
    "VERSION",
    "pyproject.toml:^version",
    "pragma-sdk/VERSION",
    "pragma-sdk/pyproject.toml:^version",
    "pragma-sdk/pragma_sdk/__init__.py:^__version",
    "price-pusher/VERSION",
    "price-pusher/pyproject.toml:^version",
    "price-pusher/price_pusher/__init__.py:^__version",
]
update_changelog_on_bump = true
changelog_incremental = true
bump_message = "bump: $current_version → $new_version"


[tool.poe.tasks]
update_abis = "find ./pragma-oracle -name '*.sierra.json' -exec cp -prv '{}' './pragma/core/abis' ';'"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"

[tool.poetry.dev-dependencies]
poethepoet = "^0.21.1"
mypy = "0.910"
ruff = "^0.4"
dunamai = "^1.7.0"
commitizen = "^2.20.3"
