[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.poetry]
name = "pragma"
version = "1.0.0"
authors = ["Pragma <contact@pragmaoracle.com>"]
description = "Core package for rollup-native Pragma Oracle"
readme = "README.md"
homepage = "https://pragmaoracle.com"
repository = "https://github.com/Astraly-Labs/Pragma"
documentation = "https://docs.pragmaoracle.com"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
packages = [
  {include = "pragma"},
  {include = "core", from = "pragma"},
  {include = "publisher", from = "pragma"},
  {include = "test", from = "pragma"},
]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
"starknet.py" = "^0.17"
cairo-lang = "^0.12"
typer = "0.6.1"
deprecated = "^1.2.14"

[tool.poetry.dev-dependencies]
black = "*"
flake8 = "*"
[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
autoflake = "^2.2.0"

