{{- if .Values.gcpSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.gcpSecrets.externalSecret.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: {{ .Values.gcpSecrets.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.gcpSecrets.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.envFromSecret.secretName }}
  dataFrom:
    - extract:
        key: {{ .Values.gcpSecrets.externalSecret.secretPath }}
{{- end }}