{{- $fullname := include "pragma-sdk.fullname" . }}
{{- range $val := .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if $val.name }}
  name: {{ $val.name }}
  {{- else if $val.suffix }}
  name: {{ $fullname }}-{{ $val.suffix }}-ingress
  {{- else }}
  name: {{ $fullname }}-ingress
  {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
    {{- with $val.annotations }}  
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if $val.className }}
  ingressClassName: {{ $val.className }}
  {{- end }}
  {{- if $val.tls }}
  tls:
    {{- range $val.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $val.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullname }}
                port: 
                  number: {{ .servicePort }}
          {{- end }}
    {{- end }}
{{- end }}