{{- if .Values.gcpSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.gcpSecrets.externalSecret.name }}-store
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcpSecrets.projectId }}
{{- end }}