{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pragma-sdk.fullname" . }}
  labels:
    {{- include "pragma-sdk.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol }}
      name: {{ .portName }}
    {{- end }}
  selector:
    {{- include "pragma-sdk.selectorLabels" . | nindent 4 }}
{{- end }}
