- pairs:
    spot:
      - BTC/USD
      - ETH/USD
      - SOL/USD
      - BNB/USD
      - LTC/USD
      - LINK/USD
      - AVAX/USD
      - MATIC/USD
      - XRP/USD
      - DOGE/USD
      - 1000PEPE/USD
      - AAVE/USD
      - TRX/USD
      - SUI/USD
      - WIF/USD
      - TIA/USD
      - TON/USD
      - LDO/USD
      - ARB/USD
      - OP/USD
      - ORDI/USD
      - JTO/USD
      - JUP/USD
      - UNI/USD
      - OKB/USD
      - ATOM/USD
      - NEAR/USD
      - 1000SATS/USD
      - ONDO/USD

  time_difference: 1
  price_deviation: 0.025