- pairs:
    spot:
      - BTC/USD
      - BTC/EUR
      - WBTC/USD
      - WBTC/BTC
      - ETH/USD
      - WSTETH/USD
      - STRK/USD
      - USDC/USD
      - USDT/USD
      - DAI/USD
  time_difference: 600
  price_deviation: 0.0025

- pairs:
    spot:
      - STETH/USD
      - LORDS/USD
      - ZEND/USD
      - NSTR/USD
      - EKUBO/USD
      - BROTHER/USDPLUS
      - xSTRK/USD
  time_difference: 600
  price_deviation: 0.025

- pairs:
    future:
      - BTC/USD
      - ETH/USD
      - BTC/USDT
      - ETH/USDT
  time_difference: 3000
  price_deviation: 0.05