spot:
  - pair: BTC/USD
  - pair: ETH/USD

future:
  - pair: BTC/USD
    expiry: 102425525524
  - pair: BTC/USD
    expiry: 0
  - pair: ETH/USD
    expiry: 234204249042
  - pair: SOL/USD
    expiry: 0
