- pairs:
    spot:
      - BTC/USD
    future:
      - BTC/USD
  time_difference: 60
  price_deviation: 0.5

- pairs:
    spot:
      - WSTETH/USD
      - USDC/USD
      - USDT/USD
  time_difference: 60
  price_deviation: 0.1
