FROM public.ecr.aws/docker/library/python:3.9

RUN apt-get update && apt-get -y install cron

RUN python -m pip install --upgrade pip

RUN pip install pragma-sdk boto3

COPY app.py .

COPY task_runner.sh /task_runner.sh
RUN chmod +x /task_runner.sh
# Run the command on container startup
ENTRYPOINT ["/task_runner.sh"]
