name: Task - Lint, Format & Typecheck

on:
  workflow_dispatch:
  workflow_call:

env:
  PYTHON_VERSION: 3.12

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --python ${{ env.PYTHON_VERSION }} --all-extras

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --verbose
        env:
          SKIP: no-commit-to-branch
