---
name: Task - Publish Package to Test PyPi

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: pragma-sdk

jobs:
  test_pypi_publish:
    name: Upload package to Test PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - run: uv build

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: pragma-sdk/dist
          attestations: false
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
