---
name: Task - Publish Package to Test PyPi

on:
  push:
    branches:
      - master

env:
  PYTHON_VERSION: 3.12.4

defaults:
  run:
    working-directory: pragma-sdk

jobs:
  test_pypi_publish:
    name: Upload package to Test PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install
        run: pip install -U build

      - name: build
        run: python -m build

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.2
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
