---
  name: Task - Publish Package
  
  on:
    workflow_dispatch:
    workflow_call:
        
  jobs:
    build_sdist:
      name: Build SDist
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: $PYTHON_VERSION
            cache: "poetry"
        - uses: CfirTsabari/actions-pipx@v1
        - name: Install poetry
          run: pipx install poetry
  
        - name: Build SDist
          run: poetry build -f sdist
  
        - uses: actions/upload-artifact@v4
          with:
            name: sdist
            path: dist
  
    upload_pypi:
      name: Upload package to PyPI
      needs: [build_sdist]
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: sdist
            path: dist
  
        - uses: pypa/gh-action-pypi-publish@release/v1
          with:
            skip-existing: true
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}