---
  name: Task - Publish Package
  
  on:
    workflow_dispatch:
    workflow_call:

  env: 
    PYTHON_VERSION: 3.12.4
  
  permissions:
    contents: read

  jobs:
    build_sdist:
      name: Build SDist
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: CfirTsabari/actions-pipx@v1
        - name: Install poetry
          run: pipx install poetry
        - uses: actions/setup-python@v5
          with:
            python-version: ${{ env.PYTHON_VERSION }}
            cache: "poetry"

        - name: Build SDist
          working-directory: ./pragma-sdk/
          run: poetry build -f sdist
  
        - uses: actions/upload-artifact@v4
          with:
            name: sdist
            path: pragma-sdk/dist/
            if-no-files-found: error
  
    pypi_test_publish:
      name: Upload package to Test PyPI
      needs: [build_sdist]
      runs-on: ubuntu-latest
      environment: testpypi
      permissions:
        id-token: write
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: sdist
            path: pragma-sdk/dist/

        - uses: pypa/gh-action-pypi-publish@release/v1
          with:
            repository-url: https://test.pypi.org/legacy/
            packages-dir: pragma-sdk/dist/
            skip-existing: true

    pypi_publish:
      name: Upload package to PyPI
      needs: [build_sdist, pypi_test_publish]
      runs-on: ubuntu-latest
      environment:
        name: pypi
        url: https://pypi.org/p/pragma-sdk
      permissions:
        id-token: write
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: sdist
            path: pragma-sdk/dist/

        - uses: pypa/gh-action-pypi-publish@release/v1
          with:
            packages-dir: pragma-sdk/dist/
            skip-existing: true
