---
  name: Task - Publish Package
  
  on:
    workflow_call:

  env: 
    PYTHON_VERSION: 3.12.4
  
  permissions:
    contents: read


  jobs:
    build_sdist:
      name: Build SDist
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: CfirTsabari/actions-pipx@v1
        - name: Install poetry
          run: pipx install poetry
        - uses: actions/setup-python@v5
          with:
            python-version: ${{ env.PYTHON_VERSION }}
            cache: "poetry"

        - name: Build SDist
          run: |
            cd pragma-sdk/
            poetry build -f sdist

        - uses: actions/upload-artifact@v4
          with:
            name: dist
            path: pragma-sdk/dist/
            if-no-files-found: error
  
    pypi_test_publish:
      name: Upload package to Test PyPI
      needs: [build_sdist]
      runs-on: ubuntu-latest
      permissions:
        id-token: write
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: dist
            path: pragma-sdk/dist/

        - uses: pypa/gh-action-pypi-publish@release/v1
          with:
            skip-existing: true
            repository-url: https://test.pypi.org/legacy/
            password: ${{ secrets.TEST_PYPI_API_TOKEN }}
            packages-dir: pragma-sdk/dist/

    pypi_publish:
      name: Upload package to PyPI
      needs: [build_sdist, pypi_test_publish]
      runs-on: ubuntu-latest
      permissions:
        id-token: write
      steps:
        - uses: actions/download-artifact@v4
          with:
            name: dist
            path: dist/

        - uses: pypa/gh-action-pypi-publish@release/v1
          with:
            skip-existing: true