---
  name: Workflow - Pull Request
  
  on:
    workflow_dispatch:
    pull_request:
      branches: [main]
  
  concurrency:
    group:
      pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true
  
  env: 
    PYTHON_VERSION: 3.12.4

  jobs:
    linters:
      name: Run linters
      uses: ./.github/workflows/linters.yml
  
    tests:
      name: Build & Integration Tests
      uses: ./.github/workflows/tests.yml