name: Stagecoach

on:
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository }}

jobs:

  # ---------------------------------------------------------- #
  # .....................BUILD IMAGES......................... #
  # ---------------------------------------------------------- #

  docker-build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [
          "stagecoach/base_images/lambda",
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.dockerfile }}:latest
            ghcr.io/${{ github.repository }}/${{ matrix.dockerfile }}:${{ github.sha }}
          file: ./${{ matrix.dockerfile }}/Dockerfile
          context: ./${{ matrix.dockerfile }}
          platforms: linux/amd64
