---
name: Task - Publish Package to Test PyPi

on:
  workflow_dispatch:
  workflow_call:


env:
  PYTHON_VERSION: 3.12.4

defaults:
  run:
    working-directory: pragma-sdk

jobs:
  test_pypi_publish:
    name: Upload package to Test PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install
        run: pip install -U build

      - name: check version
        id: check-tag
        uses: samuelcolvin/check-python-version@v4.1
        with:
          version_file_path: pragma-sdk/pragma_sdk/__init__.py

      - name: build
        run: python -m build
